// Artifact library — outputs completed agent tasks have produced.
// BioMarin Pharmaceutical.

export const ARTIFACTS = [
  {
    id: 'ART1',
    title: 'Strategy-to-Action — Q3 2026',
    type: 'pdf',
    agent: 'NOVA',
    taskType: 'Medical Insights Report',
    dateCreated: '2026-07-20',
    summary: 'Full Q3 Strategy-to-Action: ISP pillars, MO coverage, prioritised insights, proposed actions, and Gap Radar suggestions across the rare-disease portfolio (PKU, MPS/Lysosomal, Skeletal, Hemophilia A).',
    dataSources: ['MSL field notes', 'Ad board transcripts', 'Med Info queries', 'Congress debriefs', 'PubMed'],
    sizeLabel: '3.1 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART2',
    title: 'ICIEM 2025 Debrief — PALYNZIQ Adolescent PEGASUS & MPS Signals',
    type: 'pdf',
    agent: 'ARIA',
    taskType: 'Congress Debrief',
    dateCreated: '2025-09-18',
    summary: 'Synthesized read on the PEGASUS adolescent Phase 3 presentation (Kyoto) and the MPS diagnostic-delay session, with competitor visibility (Sephience) and recommended actions.',
    dataSources: ['ICIEM 2025 abstracts', 'Session transcripts', 'Social commentary'],
    sizeLabel: '2.4 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART3',
    title: 'ESPE/ESE 2025 Debrief — VOXZOGO Skeletal Data & Navepegritide Head-to-Head',
    type: 'pdf',
    agent: 'ARIA',
    taskType: 'Congress Debrief',
    dateCreated: '2025-05-16',
    summary: 'Read on VOXZOGO/CANOPY-HCH-3 hypochondroplasia data alongside Ascendis\'s navepegritide presentation at the same congress (Copenhagen) — a genuine head-to-head competitive moment. Grounds AI5 and AI7.',
    dataSources: ['ESPE/ESE 2025 abstracts', 'Session transcripts'],
    sizeLabel: '2.2 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART4',
    title: 'WFH World Congress 2026 Debrief — Hemophilia A & the Roctavian Withdrawal',
    type: 'pdf',
    agent: 'ARIA',
    taskType: 'Congress Debrief',
    dateCreated: '2026-04-25',
    summary: 'Honest read on BioMarin\'s presence at WFH 2026 (Kuala Lumpur) against the Roctavian US-withdrawal backdrop, including ex-US KOL reaction and continuity questions. Grounds AI8.',
    dataSources: ['WFH 2026 abstracts', 'Session transcripts', 'Social commentary'],
    sizeLabel: '2.0 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART5',
    title: 'ASGCT 2026 Debrief — Cross-Rare-Disease Gene & Cell Therapy Signals',
    type: 'pdf',
    agent: 'ARIA',
    taskType: 'Congress Debrief',
    dateCreated: '2026-05-19',
    summary: 'Read on ASGCT 2026 (Boston) — the congress that ties all four BioMarin therapeutic areas together thematically, including SCFE precision-messaging hallway conversations.',
    dataSources: ['ASGCT 2026 abstracts', 'Session transcripts'],
    sizeLabel: '2.1 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART6',
    title: 'SCFE Safety-Signal Precision Talking Points v1',
    type: 'pptx',
    agent: 'NOVA',
    taskType: 'Medical Insights Report',
    dateCreated: '2026-07-05',
    summary: 'Precision-messaging deck distinguishing the discontinued Turner/SHOX/ACAN CANOPY trials from the BioMarin-sponsored achondroplasia safety base, for skeletal-facing field use. Sourced from AI6, actions A9/A10.',
    dataSources: ['MSL field notes', 'Ad board transcripts', 'CANOPY program safety data'],
    sizeLabel: '2.8 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART7',
    title: 'US Roctavian Patient-Transition Protocol',
    type: 'pdf',
    agent: 'NOVA',
    taskType: 'Field Enablement',
    dateCreated: '2026-05-22',
    summary: 'Concrete, field-ready protocol for US hemophilia treatment centers navigating the May 2026 withdrawal, covering last-dosing dates and follow-up commitments for previously-treated patients. Sourced from AI9, action A14.',
    dataSources: ['MSL field notes', 'Med Info queries'],
    sizeLabel: '1.6 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART8',
    title: 'ICIEM → ESPE/ESE → WFH → ASGCT Sentiment Trend',
    type: 'interactive',
    agent: 'ARIA',
    taskType: 'Congress Intelligence',
    dateCreated: '2026-07-18',
    summary: 'Cross-congress sentiment shift across the rare-disease portfolio themes, competitor visibility, and social amplification from ICIEM 2025 through ASGCT 2026.',
    dataSources: ['ICIEM 2025 abstracts', 'ESPE/ESE 2025 abstracts', 'WFH 2026 abstracts', 'ASGCT 2026 abstracts', 'Social commentary'],
    sizeLabel: 'In-app',
    provenance: 'synthesized',
  },
];
