// Actionable insights — BioMarin Pharmaceutical. Grounded in the MO/LP
// spine and each franchise's real evidence base and competitive pressures.

export const INSIGHTS = [
  {
    id: 'AI1',
    title: 'Community geneticists weighing Sephience switch for stable KUVAN patients',
    priority: 'High',
    lpRefs: ['LP1'],
    moRefs: ['MO1'],
    recurrence: 4,
    recency: '2026-06',
    summary: "MSL interactions show BH4-responsive PKU prescribers actively evaluating Sephience's once-daily oral profile as a simplification opportunity for stable KUVAN patients, even absent a clear efficacy gap — the first real switching pressure KUVAN has faced since its own approval.",
    sourceInsights: [
      { type: 'MSL interaction', role: 'Biochemical geneticist', location: 'Salt Lake City, UT', quote: 'My stable KUVAN patients are asking about Sephience because they heard it\'s "the newer one" — I don\'t have a clean answer for why they shouldn\'t switch.', date: '2026-06-04' },
      { type: 'Ad board', role: 'Biochemical geneticist', location: 'Pittsburgh, PA', quote: 'We need a direct, honest comparison — not a defensive one — or we lose credibility with families who will find PTC\'s materials on their own.', date: '2026-05-19' },
      { type: 'Med Info query', role: 'Metabolic dietitian', location: 'Portland, OR', quote: 'Is there head-to-head data on KUVAN vs. Sephience, or just separate placebo-controlled trials?', date: '2026-06-11' },
      { type: 'Congress debrief', role: 'Biochemical geneticist', location: 'ICIEM 2025', quote: 'Sephience\'s Kyoto session was well attended — the once-daily dosing message landed clearly with the community audience.', date: '2025-09-10' },
    ],
    status: 'Prioritised',
    confidenceScore: 0.88,
    provenance: 'synthesized',
  },
  {
    id: 'AI2',
    title: 'Adolescent PALYNZIQ initiation hesitancy despite PEGASUS data',
    priority: 'High',
    lpRefs: ['LP2'],
    moRefs: ['MO2'],
    recurrence: 3,
    recency: '2026-06',
    summary: 'Pediatric geneticists cite injection-site reaction and anaphylaxis-monitoring burden as the real adoption barrier for newly-eligible adolescents, even where PEGASUS efficacy data (blood Phe −473 vs. −19 µmol/L at week 72) is well understood and well received.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'Pediatric geneticist', location: 'Boston, MA', quote: 'The efficacy data is compelling — my hesitation is entirely about whether a 14-year-old and their family can manage the dose-escalation and monitoring burden at home.', date: '2026-06-08' },
      { type: 'Med Info query', role: 'Pediatric endocrinologist', location: 'Chicago, IL', quote: 'What does the adolescent anaphylaxis-monitoring protocol actually look like in practice versus the adult protocol?', date: '2026-06-15' },
      { type: 'Ad board', role: 'Metabolic dietitian', location: 'Virtual', quote: 'Families need a plain-language adolescent-specific starter guide — the adult materials read as not-for-them.', date: '2026-05-27' },
    ],
    status: 'Validated',
    confidenceScore: 0.83,
    provenance: 'synthesized',
  },
  {
    id: 'AI3',
    title: 'MSLs and physicians both underinformed on Aldurazyme\'s co-marketing structure',
    priority: 'Medium',
    lpRefs: ['LP3'],
    moRefs: ['MO3'],
    recurrence: 2,
    recency: '2026-04',
    summary: 'Field reports surface real confusion — including among BioMarin\'s own field team — about whether BioMarin or Genzyme/Sanofi is the right first call for Aldurazyme supply, dosing support, or adverse-event reporting questions.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'MSL (internal)', location: 'Lyon, France', quote: 'I had a physician ask me an Aldurazyme access question and I honestly wasn\'t sure whether that routes through us or through Genzyme.', date: '2026-04-12' },
      { type: 'Med Info query', role: 'Pediatric metabolic specialist', location: 'Wiesbaden, Germany', quote: 'Who do I actually call for an Aldurazyme supply issue — BioMarin or Sanofi?', date: '2026-04-22' },
    ],
    status: 'Triaged',
    confidenceScore: 0.74,
    provenance: 'synthesized',
  },
  {
    id: 'AI4',
    title: 'MPS diagnostic delay persists at the community-to-specialist referral handoff',
    priority: 'High',
    lpRefs: ['LP4'],
    moRefs: ['MO3'],
    recurrence: 3,
    recency: '2026-05',
    summary: 'Referral-pathway gaps for MPS VI, IVA, and CLN2 remain concentrated at the community pediatrician level — nonspecific early symptoms and low disease awareness delay specialist referral well past the point where earlier enzyme replacement therapy initiation would matter most.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'Biochemical geneticist', location: 'Chapel Hill, NC', quote: 'By the time these patients reach me, we\'ve usually lost a year or more to nonspecific symptom workups in primary care.', date: '2026-05-06' },
      { type: 'Congress debrief', role: 'Biochemical geneticist', location: 'ICIEM 2025', quote: 'The Kyoto diagnostic-delay session confirmed this isn\'t a US-specific problem — it\'s consistent across the reference-center network globally.', date: '2025-09-11' },
      { type: 'Ad board', role: 'Community pediatrician', location: 'Oakland, CA', quote: 'I see maybe one suspected MPS case in a career — I need a simple screening checklist, not a specialist-level differential.', date: '2026-04-30' },
    ],
    status: 'Validated',
    confidenceScore: 0.81,
    provenance: 'synthesized',
  },
  {
    id: 'AI5',
    title: 'Skeletal-dysplasia specialists requesting hypochondroplasia expansion timeline clarity',
    priority: 'Medium',
    lpRefs: ['LP5'],
    moRefs: ['MO4'],
    recurrence: 3,
    recency: '2026-07',
    summary: 'Following CANOPY-HCH-3\'s positive Phase 3 readout, specialists are proactively asking when hypochondroplasia families can expect an approved VOXZOGO option — MSLs report a real risk of off-label pressure building ahead of the Q3 2026 sNDA filing.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'Clinical geneticist', location: 'Baltimore, MD', quote: 'I have three hypochondroplasia families asking me this month whether they should just push for off-label access now rather than wait for the filing.', date: '2026-07-02' },
      { type: 'Congress debrief', role: 'Pediatric endocrinologist', location: 'ESPE/ESE 2025', quote: 'The CANOPY-HCH-3 data presentation in Copenhagen generated real excitement — and real impatience about timeline.', date: '2025-05-12' },
    ],
    status: 'Prioritised',
    confidenceScore: 0.78,
    provenance: 'synthesized',
  },
  {
    id: 'AI6',
    title: 'SCFE safety-signal questions bleeding into achondroplasia conversations',
    priority: 'High',
    lpRefs: ['LP6'],
    moRefs: ['MO4'],
    recurrence: 4,
    recency: '2026-07',
    summary: 'Despite the SCFE signal being confined to discontinued Turner/SHOX/ACAN investigator-sponsored trials, MSL field reports show some community endocrinologists are now asking general achondroplasia safety questions that conflate the two — a precision-of-messaging problem, not a new achondroplasia signal.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'Pediatric endocrinologist', location: 'London, UK', quote: 'I saw the SCFE news and now I\'m double-checking — is this something I need to worry about in my achondroplasia patients too?', date: '2026-07-08' },
      { type: 'Med Info query', role: 'Community endocrinologist', location: 'Baltimore, MD', quote: 'Can you confirm whether the SCFE cases were in achondroplasia patients or a different population?', date: '2026-07-14' },
      { type: 'Ad board', role: 'Clinical geneticist', location: 'London, UK', quote: 'The distinction matters enormously and I don\'t think it\'s landing cleanly in the community — precision here protects both patient trust and the achondroplasia franchise.', date: '2026-06-25' },
      { type: 'Congress debrief', role: 'Skeletal dysplasia specialist', location: 'ASGCT 2026', quote: 'Hallway conversations in Boston showed real appetite for a clear, one-page distinction document.', date: '2026-05-13' },
    ],
    status: 'Prioritised',
    confidenceScore: 0.86,
    provenance: 'synthesized',
  },
  {
    id: 'AI7',
    title: 'Skeletal KOL attention shifting toward navepegritide ahead of EU decision',
    priority: 'Medium',
    lpRefs: ['LP7'],
    moRefs: ['MO5'],
    recurrence: 2,
    recency: '2026-06',
    summary: "Field and congress signals show at least one mid-tier European skeletal KOL (Klaus Mohnike) engaging more closely with Ascendis's navepegritide data as its Q4 2026 EU regulatory decision approaches — a defensible, timeline-driven attention shift, not a rupture, but worth a proactive BMN 333 conversation before the decision lands.",
    sourceInsights: [
      { type: 'Congress debrief', role: 'Pediatric endocrinologist', location: 'ESPE/ESE 2025', quote: 'Dr. Mohnike asked unusually detailed follow-up questions in the navepegritide session — more than I\'d expect from someone purely BioMarin-aligned.', date: '2025-05-11' },
      { type: 'MSL interaction', role: 'Field Medical (Continental Europe)', location: 'Magdeburg, Germany', quote: 'He\'s not negative on VOXZOGO, but he\'s clearly tracking the once-weekly dosing conversation closely as the EU filing timeline gets nearer.', date: '2026-06-02' },
    ],
    status: 'Validated',
    confidenceScore: 0.69,
    provenance: 'synthesized',
  },
  {
    id: 'AI8',
    title: 'Ex-US hemophilia KOLs seeking clarity on Roctavian\'s post-withdrawal availability',
    priority: 'High',
    lpRefs: ['LP8'],
    moRefs: ['MO6'],
    recurrence: 3,
    recency: '2026-06',
    summary: 'UK, EU, and international hemophilia treaters are asking direct questions about whether the US withdrawal signals a broader retreat, and whether ex-US availability and scientific support will continue at the same level — an ex-US-credibility risk if left unaddressed.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'Hematologist', location: 'Rotterdam, Netherlands', quote: 'My patients are asking me directly if this means Roctavian is going away everywhere — I need a clear answer, not corporate language.', date: '2026-06-09' },
      { type: 'Congress debrief', role: 'Hematologist', location: 'WFH World Congress 2026', quote: 'The Kuala Lumpur hallway conversation was dominated by the US news — ex-US colleagues want to know this isn\'t the first domino.', date: '2026-04-20' },
      { type: 'Ad board', role: 'Hematologist', location: 'London, UK', quote: 'Continued scientific engagement from BioMarin matters more now than it did a year ago, precisely because the US news raises doubt.', date: '2026-05-15' },
    ],
    status: 'Prioritised',
    confidenceScore: 0.84,
    provenance: 'synthesized',
  },
  {
    id: 'AI9',
    title: 'US treaters requesting a concrete patient-transition protocol ahead of May 2026 withdrawal',
    priority: 'High',
    lpRefs: ['LP8'],
    moRefs: ['MO6'],
    recurrence: 3,
    recency: '2026-05',
    summary: 'US hemophilia treatment centers report needing a concrete, honest protocol for patients currently infused or actively considering Roctavian before the withdrawal date — MSLs note the absence of a single, clear field-facing document is creating inconsistent messaging across centers.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'Hematologist', location: 'Ann Arbor, MI', quote: 'I have patients mid-evaluation right now. I need to know exactly what to tell them, and I need it in writing, not a verbal MSL summary.', date: '2026-05-11' },
      { type: 'Med Info query', role: 'Hematologist', location: 'San Francisco, CA', quote: 'What is the actual last date a US patient can be dosed, and what follow-up commitment does BioMarin have for patients already treated?', date: '2026-05-20' },
    ],
    status: 'Validated',
    confidenceScore: 0.82,
    provenance: 'synthesized',
  },
];
