// KOL roster — BioMarin Pharmaceutical. 32 real, verified physicians across
// PKU/biochemical genetics, MPS/lysosomal storage disorders, skeletal
// conditions/pediatric endocrinology, and hemophilia A/gene therapy.
// Sourced from research/RESEARCH_SUMMARY.md. Locked roster — do not add or
// drop names.
//
// productAlignment is TA-level (broad) for most KOLs given 8 products
// across 4 TAs — see DEMO_BRIEF_TEMPLATE.md / research summary §3.
// engagementTier is a string ('Tier 1' / 'Tier 2' / 'Tier 3'), never numeric.
// influenceScore, recentInteractions, publications, conferenceAppearances
// are plausible synthesis; identities, affiliations, and trial connections
// are real and verified.
//
// Christian Hendriksz's current institution is genuinely unresolved between
// UK and South Africa sources (see research flags) — used as an in-universe
// field-coverage-gap narrative device, not a sentiment story.
//
// Klaus Mohnike is the divergence/sentiment-shift KOL (see config/insights.js
// AI7, config/predictive-signals.js ps-4, config/vega.js sentiment velocity):
// as Ascendis's navepegritide moves toward its Q4 2026 EU decision, his
// congress commentary has grown more attentive to the competitor data —
// a defensible, European-regulatory-timeline-driven sentiment cooling, not
// an invented rupture.

export const KOL_DATA = [
  // ── PKU / Biochemical Genetics (4) ──────────────────────────────────────
  {
    id: 'kol-1',
    name: 'Jerry Vockley, MD, PhD, FACMG',
    institution: 'University of Pittsburgh / UPMC Children\'s Hospital of Pittsburgh',
    city: 'Pittsburgh',
    country: 'USA',
    region: 'North America',
    specialty: 'Biochemical genetics',
    influenceScore: 94,
    engagementTier: 'Tier 1',
    productAlignment: ['kuvan', 'palynziq'],
    recentInteractions: 9,
    publications: 412,
    focusAreas: ['PKU natural history', 'BH4-responsiveness', 'Newborn screening policy'],
    conferenceAppearances: 13,
    recommendedStrategy: 'One of the most cited voices on PKU natural history and BH4-responsiveness — the exact clinical question Sephience\'s entry has reopened. Priority engagement for MO1 (KUVAN retention) scientific exchange ahead of ACMG 2027.',
  },
  {
    id: 'kol-2',
    name: 'Nicola Longo, MD, PhD',
    institution: 'University of Utah',
    city: 'Salt Lake City',
    country: 'USA',
    region: 'North America',
    specialty: 'Biochemical genetics',
    influenceScore: 90,
    engagementTier: 'Tier 1',
    productAlignment: ['kuvan', 'palynziq'],
    recentInteractions: 8,
    publications: 356,
    focusAreas: ['PKU dietary management', 'PAL enzyme substitution', 'Adult PKU transition'],
    conferenceAppearances: 11,
    recommendedStrategy: 'Deep bench in both BH4 cofactor and PAL enzyme-substitution therapy — well positioned to speak credibly to the KUVAN-vs-PALYNZIQ-vs-Sephience decision tree community geneticists are now navigating (MO1).',
  },
  {
    id: 'kol-3',
    name: 'Cary O. Harding, MD',
    institution: 'Oregon Health & Science University (OHSU)',
    city: 'Portland',
    country: 'USA',
    region: 'North America',
    specialty: 'Biochemical genetics',
    influenceScore: 84,
    engagementTier: 'Tier 2',
    productAlignment: ['kuvan', 'palynziq'],
    recentInteractions: 6,
    publications: 218,
    focusAreas: ['PKU gene therapy landscape', 'Metabolic control long-term outcomes'],
    conferenceAppearances: 9,
    recommendedStrategy: 'Regional West Coast anchor with a research lens on the broader PKU gene-therapy landscape — useful for framing BMN 307\'s clinical-hold status accurately if asked, without overstating near-term pipeline activity.',
  },
  {
    id: 'kol-4',
    name: 'Harvey Levy, MD',
    institution: 'Boston Children\'s Hospital / Harvard Medical School',
    city: 'Boston',
    country: 'USA',
    region: 'North America',
    specialty: 'Biochemical genetics',
    influenceScore: 92,
    engagementTier: 'Tier 1',
    productAlignment: ['kuvan', 'palynziq'],
    recentInteractions: 7,
    publications: 389,
    focusAreas: ['Newborn screening pioneer', 'PKU natural history', 'Adolescent PAL therapy'],
    conferenceAppearances: 10,
    recommendedStrategy: 'PKU newborn-screening pioneer whose historical credibility carries real weight in adolescent-transition conversations — a strong voice for the PALYNZIQ adolescent (PEGASUS) narrative (MO2).',
  },

  // ── MPS / Lysosomal Storage Disorders (9) ───────────────────────────────
  {
    id: 'kol-5',
    name: 'Joseph Muenzer, MD, PhD',
    institution: 'University of North Carolina at Chapel Hill',
    city: 'Chapel Hill',
    country: 'USA',
    region: 'North America',
    specialty: 'Biochemical genetics / MPS',
    influenceScore: 93,
    engagementTier: 'Tier 1',
    productAlignment: ['naglazyme', 'vimizim', 'aldurazyme', 'brineura'],
    recentInteractions: 9,
    publications: 401,
    focusAreas: ['MPS disease-modifying therapy consensus', 'Enzyme replacement long-term outcomes'],
    conferenceAppearances: 12,
    recommendedStrategy: 'Broadest MPS-franchise credibility on the roster — a strong first call for any MO3 field-excellence or Aldurazyme co-marketing-clarity conversation across the full four-product MPS bench.',
  },
  {
    id: 'kol-6',
    name: 'Christian J. Hendriksz, MD',
    institution: 'Institution unconfirmed (see coverage note)',
    city: 'Not confirmed',
    country: 'Not confirmed',
    region: 'International',
    specialty: 'Biochemical genetics / MPS IVA',
    influenceScore: 71,
    engagementTier: 'Tier 2',
    productAlignment: ['vimizim', 'naglazyme'],
    recentInteractions: 2,
    publications: 187,
    focusAreas: ['MPS IVA (Morquio A)', 'Vimizim pivotal trial'],
    conferenceAppearances: 4,
    recommendedStrategy: 'Genuine field-coverage gap, not a sentiment issue: Hendriksz\'s current institutional home is unconfirmed in our records following a prior career move, and MSL contact has lapsed accordingly. His historical role on the Vimizim pivotal program (MOR-004) makes him worth re-locating rather than writing off — flagged in Gap Radar.',
  },
  {
    id: 'kol-7',
    name: 'Nathalie Guffon, MD',
    institution: 'Hôpital Femme Mère Enfant',
    city: 'Lyon',
    country: 'France',
    region: 'Europe',
    specialty: 'Pediatric metabolic disease / MPS',
    influenceScore: 85,
    engagementTier: 'Tier 1',
    productAlignment: ['naglazyme', 'vimizim', 'aldurazyme', 'brineura'],
    recentInteractions: 6,
    publications: 264,
    focusAreas: ['MPS I/VI long-term follow-up', 'French rare-disease reference-center network'],
    conferenceAppearances: 8,
    recommendedStrategy: 'Reference-center leadership in the French MPS network — a natural anchor for Aldurazyme co-marketing-clarity conversations given her direct visibility into the Genzyme-commercialized side of MPS I care (MO3).',
  },
  {
    id: 'kol-8',
    name: 'Angela Schulz, MD, PhD',
    institution: 'University Medical Center Hamburg-Eppendorf (UKE)',
    city: 'Hamburg',
    country: 'Germany',
    region: 'Europe',
    specialty: 'Pediatric neurology / CLN2',
    influenceScore: 87,
    engagementTier: 'Tier 1',
    productAlignment: ['brineura', 'naglazyme', 'vimizim'],
    recentInteractions: 7,
    publications: 233,
    focusAreas: ['CLN2 disease (Batten disease)', 'Intraventricular enzyme delivery'],
    conferenceAppearances: 9,
    recommendedStrategy: 'Leading European CLN2/Batten voice — Brineura\'s highest-priority scientific-exchange partner for intraventricular-delivery protocol questions and long-term neurodevelopmental outcomes data (MO3).',
  },
  {
    id: 'kol-9',
    name: 'Paul Harmatz, MD',
    institution: 'UCSF Benioff Children\'s Hospital Oakland',
    city: 'Oakland',
    country: 'USA',
    region: 'North America',
    specialty: 'Pediatric gastroenterology / MPS',
    influenceScore: 91,
    engagementTier: 'Tier 1',
    productAlignment: ['naglazyme', 'vimizim', 'aldurazyme', 'brineura'],
    recentInteractions: 8,
    publications: 347,
    focusAreas: ['MPS clinical trial design', 'Endpoint development', 'Real-world outcomes registries'],
    conferenceAppearances: 11,
    recommendedStrategy: 'Deep trial-methodology credibility across the MPS franchise — a strong voice for framing real-world MPS diagnostic-delay and referral-pathway data (AI4, MO3).',
  },
  {
    id: 'kol-10',
    name: 'Barbara K. Burton, MD',
    institution: 'Ann & Robert H. Lurie Children\'s Hospital / Northwestern Feinberg School of Medicine',
    city: 'Chicago',
    country: 'USA',
    region: 'North America',
    specialty: 'Biochemical genetics / MPS',
    influenceScore: 88,
    engagementTier: 'Tier 1',
    productAlignment: ['naglazyme', 'vimizim', 'aldurazyme', 'brineura', 'kuvan'],
    recentInteractions: 7,
    publications: 298,
    focusAreas: ['MPS newborn screening', 'Cross-lysosomal-disorder diagnosis pathways'],
    conferenceAppearances: 10,
    recommendedStrategy: 'Cross-lysosomal-disorder diagnostic-pathway expertise makes her a strong candidate for the MO3 referral-pathway listening priority, particularly on closing time-to-diagnosis gaps in community pediatric practices.',
  },
  {
    id: 'kol-11',
    name: 'Roberto Giugliani, MD, PhD',
    institution: 'UFRGS / Hospital de Clínicas de Porto Alegre',
    city: 'Porto Alegre',
    country: 'Brazil',
    region: 'Latin America',
    specialty: 'Medical genetics / MPS',
    influenceScore: 86,
    engagementTier: 'Tier 1',
    productAlignment: ['naglazyme', 'vimizim', 'aldurazyme', 'brineura'],
    recentInteractions: 5,
    publications: 312,
    focusAreas: ['Latin American MPS registries', 'Newborn screening expansion'],
    conferenceAppearances: 9,
    recommendedStrategy: 'The strongest Latin American MPS voice on the roster — key for extending referral-pathway and diagnostic-delay listening beyond the US/EU-heavy field footprint (MO3), coordinated via Dr. Amara Okafor\'s international coverage.',
  },
  {
    id: 'kol-12',
    name: 'Christina Lampe, MD',
    institution: 'Dr. Horst Schmidt Klinik, Center for Rare Diseases',
    city: 'Wiesbaden',
    country: 'Germany',
    region: 'Europe',
    specialty: 'Pediatric metabolic disease / MPS',
    influenceScore: 78,
    engagementTier: 'Tier 2',
    productAlignment: ['naglazyme', 'vimizim', 'aldurazyme'],
    recentInteractions: 5,
    publications: 176,
    focusAreas: ['MPS cardiac and orthopedic complications', 'Multidisciplinary MPS care'],
    conferenceAppearances: 6,
    recommendedStrategy: 'Multidisciplinary-care angle (cardiac/orthopedic complications) is a useful complement to Guffon and Schulz for German-network MO3 field coverage.',
  },
  {
    id: 'kol-13',
    name: 'Stephanie Sacharow, MD',
    institution: 'Boston Children\'s Hospital / Harvard Medical School',
    city: 'Boston',
    country: 'USA',
    region: 'North America',
    specialty: 'Biochemical genetics — dual PKU/lysosomal',
    influenceScore: 80,
    engagementTier: 'Tier 2',
    productAlignment: ['kuvan', 'palynziq', 'naglazyme', 'vimizim', 'aldurazyme', 'brineura'],
    recentInteractions: 6,
    publications: 154,
    focusAreas: ['PEGASUS adolescent PALYNZIQ trial', 'Cross-disorder biochemical genetics'],
    conferenceAppearances: 7,
    recommendedStrategy: 'The roster\'s clearest cross-indication cluster member — dual PKU/lysosomal focus and a PEGASUS trial connection make her the natural anchor for Auri\'s cross-franchise queries spanning MO2 (adolescent PALYNZIQ) and MO3 (MPS field excellence).',
  },

  // ── Skeletal Conditions / Pediatric Endocrinology (10) ──────────────────
  {
    id: 'kol-14',
    name: 'Ravi Savarirayan, MD',
    institution: 'Murdoch Children\'s Research Institute / Royal Children\'s Hospital',
    city: 'Melbourne',
    country: 'Australia',
    region: 'Asia-Pacific',
    specialty: 'Clinical genetics / skeletal dysplasia',
    influenceScore: 97,
    engagementTier: 'Tier 1',
    productAlignment: ['voxzogo', 'bmn-333'],
    recentInteractions: 8,
    publications: 289,
    focusAreas: ['Vosoritide pivotal trial (lead investigator)', 'Achondroplasia consensus guidelines', 'Hypochondroplasia expansion'],
    conferenceAppearances: 14,
    recommendedStrategy: 'Lead investigator on the vosoritide pivotal program and first author on the achondroplasia consensus guidelines — the single highest-priority engagement on the entire roster for MO4/MO5 hypochondroplasia-expansion and BMN 333 successor-positioning conversations.',
  },
  {
    id: 'kol-15',
    name: 'Melita Irving, MD',
    institution: 'Guy\'s and St Thomas\' NHS Foundation Trust / Evelina London Children\'s Hospital',
    city: 'London',
    country: 'UK',
    region: 'Europe',
    specialty: 'Clinical genetics / skeletal dysplasia',
    influenceScore: 88,
    engagementTier: 'Tier 1',
    productAlignment: ['voxzogo', 'bmn-333'],
    recentInteractions: 7,
    publications: 201,
    focusAreas: ['Achondroplasia natural history', 'CANOPY program safety monitoring'],
    conferenceAppearances: 10,
    recommendedStrategy: 'UK reference-center visibility into the CANOPY program\'s safety-monitoring infrastructure — a credible, careful voice for the SCFE safety-signal listening priority (LP6/MO4) precisely because she does not overclaim on either side of it.',
  },
  {
    id: 'kol-16',
    name: 'Julie Hoover-Fong, MD, PhD',
    institution: 'Johns Hopkins University (Greenberg Center for Skeletal Dysplasias)',
    city: 'Baltimore',
    country: 'USA',
    region: 'North America',
    specialty: 'Clinical genetics / skeletal dysplasia',
    influenceScore: 89,
    engagementTier: 'Tier 1',
    productAlignment: ['voxzogo', 'bmn-333'],
    recentInteractions: 8,
    publications: 246,
    focusAreas: ['Achondroplasia growth registries', 'Skeletal dysplasia natural history'],
    conferenceAppearances: 11,
    recommendedStrategy: 'Registry-data depth makes her the strongest US voice for grounding SCFE safety-signal conversations in the BioMarin-sponsored achondroplasia dataset (>5,000 patients, no SCFE cases) rather than the discontinued investigator-sponsored Turner/SHOX/ACAN trials.',
  },
  {
    id: 'kol-17',
    name: 'Klaus Mohnike, MD',
    institution: 'Otto-von-Guericke University Magdeburg',
    city: 'Magdeburg',
    country: 'Germany',
    region: 'Europe',
    specialty: 'Pediatric endocrinology / skeletal dysplasia',
    influenceScore: 79,
    engagementTier: 'Tier 2',
    productAlignment: ['voxzogo', 'bmn-333'],
    recentInteractions: 4,
    publications: 168,
    focusAreas: ['German achondroplasia treatment network', 'CNP-analog comparative positioning'],
    conferenceAppearances: 7,
    recommendedStrategy: 'Sentiment-shift watch: recent ESPE/ESE 2025 commentary and follow-up correspondence show growing attentiveness to Ascendis\'s navepegritide data as its EU regulatory decision (Q4 2026) approaches — a defensible, timeline-driven cooling worth a proactive BMN 333 scientific-exchange before the decision lands (see AI7, ps-4).',
  },
  {
    id: 'kol-18',
    name: 'Bradley S. Miller, MD, PhD',
    institution: 'University of Minnesota Medical School',
    city: 'Minneapolis',
    country: 'USA',
    region: 'North America',
    specialty: 'Pediatric endocrinology',
    influenceScore: 85,
    engagementTier: 'Tier 1',
    productAlignment: ['voxzogo', 'bmn-333'],
    recentInteractions: 6,
    publications: 219,
    focusAreas: ['Growth hormone / CNP comparative endocrinology', 'Noonan syndrome growth'],
    conferenceAppearances: 9,
    recommendedStrategy: 'Growth-endocrinology cross-training gives him useful standing on the Noonan syndrome Phase 2 program, one of the two skeletal indications still actively enrolling post-Mar 2026 (alongside idiopathic short stature).',
  },
  {
    id: 'kol-19',
    name: 'Valérie Cormier-Daire, MD, PhD',
    institution: 'Hôpital Necker-Enfants Malades / Institut Imagine, Université Paris Cité',
    city: 'Paris',
    country: 'France',
    region: 'Europe',
    specialty: 'Clinical genetics / skeletal dysplasia',
    influenceScore: 90,
    engagementTier: 'Tier 1',
    productAlignment: ['voxzogo', 'bmn-333'],
    recentInteractions: 7,
    publications: 274,
    focusAreas: ['Achondroplasia consensus guidelines co-author', 'Hypochondroplasia genetics'],
    conferenceAppearances: 10,
    recommendedStrategy: 'Consensus-guidelines co-author with deep hypochondroplasia genetics expertise — a priority engagement ahead of the Q3 2026 hypochondroplasia sNDA filing (MO4).',
  },
  {
    id: 'kol-20',
    name: 'Mohamad Maghnie, MD',
    institution: 'IRCCS Istituto Giannina Gaslini / University of Genoa',
    city: 'Genoa',
    country: 'Italy',
    region: 'Europe',
    specialty: 'Pediatric endocrinology',
    influenceScore: 81,
    engagementTier: 'Tier 2',
    productAlignment: ['voxzogo', 'bmn-333'],
    recentInteractions: 5,
    publications: 205,
    focusAreas: ['Consensus guidelines co-author', 'Italian achondroplasia treatment network'],
    conferenceAppearances: 8,
    recommendedStrategy: 'Italian-network anchor and consensus-guidelines co-author — pairs well with Cormier-Daire for coordinated Southern European hypochondroplasia-expansion messaging.',
  },
  {
    id: 'kol-21',
    name: 'Philippe Backeljauw, MD',
    institution: 'Cincinnati Children\'s Hospital Medical Center',
    city: 'Cincinnati',
    country: 'USA',
    region: 'North America',
    specialty: 'Pediatric endocrinology',
    influenceScore: 87,
    engagementTier: 'Tier 1',
    productAlignment: ['voxzogo', 'bmn-333'],
    recentInteractions: 6,
    publications: 231,
    focusAreas: ['Consensus guidelines co-author', 'Turner syndrome endocrinology'],
    conferenceAppearances: 9,
    recommendedStrategy: 'Turner syndrome endocrinology background makes him an important, careful voice for accurately communicating that CANOPY Turner-syndrome dosing was discontinued (Mar 2026 SCFE signal) without overclaiming into unrelated achondroplasia safety.',
  },
  {
    id: 'kol-22',
    name: 'Keiichi Ozono, MD, PhD',
    institution: 'Osaka University Graduate School of Medicine',
    city: 'Osaka',
    country: 'Japan',
    region: 'Asia-Pacific',
    specialty: 'Pediatric endocrinology',
    influenceScore: 82,
    engagementTier: 'Tier 2',
    productAlignment: ['voxzogo', 'bmn-333'],
    recentInteractions: 4,
    publications: 197,
    focusAreas: ['Consensus guidelines co-author', 'Japanese achondroplasia treatment network'],
    conferenceAppearances: 7,
    recommendedStrategy: 'Primary Japan-market voice for VOXZOGO and BMN 333 — coordinated via Dr. Amara Okafor\'s international coverage for APAC-region field excellence.',
  },
  {
    id: 'kol-23',
    name: 'Svein Otto Fredwall, MD, PhD',
    institution: 'TRS National Resource Centre / Oslo University Hospital Rikshospitalet',
    city: 'Oslo',
    country: 'Norway',
    region: 'Europe',
    specialty: 'Rehabilitation medicine / skeletal dysplasia',
    influenceScore: 77,
    engagementTier: 'Tier 2',
    productAlignment: ['voxzogo', 'bmn-333'],
    recentInteractions: 4,
    publications: 143,
    focusAreas: ['Consensus guidelines co-author', 'Functional outcomes in achondroplasia'],
    conferenceAppearances: 6,
    recommendedStrategy: 'Functional-outcomes lens (mobility, quality of life) rounds out the consensus-guidelines cohort with a patient-centered angle useful for Nordic-network scientific exchange.',
  },

  // ── Hemophilia A / Gene Therapy (9) ──────────────────────────────────────
  {
    id: 'kol-24',
    name: 'Steven W. Pipe, MD',
    institution: 'University of Michigan, C.S. Mott Children\'s Hospital',
    city: 'Ann Arbor',
    country: 'USA',
    region: 'North America',
    specialty: 'Pediatric hematology / hemophilia gene therapy',
    influenceScore: 95,
    engagementTier: 'Tier 1',
    productAlignment: ['roctavian'],
    recentInteractions: 6,
    publications: 356,
    focusAreas: ['GENEr8-1 pivotal trial', '5-year durability data', 'Gene therapy field leadership'],
    conferenceAppearances: 12,
    recommendedStrategy: 'GENEr8-1 pivotal-trial credibility makes him the single most important voice for the MO6 US-exit narrative — his continued scientific engagement (durable 5-yr data, ~80.8% off prophylaxis) is exactly the ex-US credibility asset worth preserving deliberately as the US commercial presence winds down.',
  },
  {
    id: 'kol-25',
    name: 'Barbara A. Konkle, MD',
    institution: 'Bloodworks Northwest / Washington Center for Bleeding Disorders',
    city: 'Seattle',
    country: 'USA',
    region: 'North America',
    specialty: 'Hematology / hemophilia',
    influenceScore: 88,
    engagementTier: 'Tier 1',
    productAlignment: ['roctavian'],
    recentInteractions: 4,
    publications: 298,
    focusAreas: ['Hemophilia treatment center network', 'Gene therapy patient selection'],
    conferenceAppearances: 8,
    recommendedStrategy: 'Deep US hemophilia treatment-center network visibility — important for informing the divestiture evaluation with real field intelligence on how existing US Roctavian patients are being counseled through the withdrawal transition.',
  },
  {
    id: 'kol-26',
    name: 'Frank W.G. Leebeek, MD, PhD',
    institution: 'Erasmus University Medical Center',
    city: 'Rotterdam',
    country: 'Netherlands',
    region: 'Europe',
    specialty: 'Hematology / hemophilia',
    influenceScore: 86,
    engagementTier: 'Tier 1',
    productAlignment: ['roctavian'],
    recentInteractions: 5,
    publications: 341,
    focusAreas: ['European hemophilia gene therapy network', 'Long-term factor VIII durability'],
    conferenceAppearances: 9,
    recommendedStrategy: 'A priority ex-US scientific-credibility engagement — Roctavian remains commercially available outside the US, and Leebeek\'s continued advocacy is a real asset to preserve deliberately through the US-exit transition (MO6).',
  },
  {
    id: 'kol-27',
    name: 'Johnny Mahlangu, MD',
    institution: 'University of the Witwatersrand',
    city: 'Johannesburg',
    country: 'South Africa',
    region: 'Africa',
    specialty: 'Hematology / hemophilia',
    influenceScore: 84,
    engagementTier: 'Tier 2',
    productAlignment: ['roctavian'],
    recentInteractions: 3,
    publications: 276,
    focusAreas: ['GENEr8-1 co-investigator', 'Global hemophilia access'],
    conferenceAppearances: 8,
    recommendedStrategy: 'GENEr8-1 co-investigator with global-access standing — coordinated via Dr. Amara Okafor for the international/RoW MO6 ex-US-credibility thread.',
  },
  {
    id: 'kol-28',
    name: 'Stacy E. Croteau, MD, MMS',
    institution: 'Boston Children\'s Hospital / Boston Hemophilia Center',
    city: 'Boston',
    country: 'USA',
    region: 'North America',
    specialty: 'Pediatric hematology / hemophilia',
    influenceScore: 83,
    engagementTier: 'Tier 1',
    productAlignment: ['roctavian'],
    recentInteractions: 4,
    publications: 219,
    focusAreas: ['Adolescent-to-adult hemophilia transition', 'Gene therapy counseling'],
    conferenceAppearances: 7,
    recommendedStrategy: 'Transition-of-care expertise is directly relevant to counseling families of patients approaching adulthood through the US withdrawal window — a sensitive but important MO6 field conversation.',
  },
  {
    id: 'kol-29',
    name: 'Margareth C. Ozelo, MD, PhD',
    institution: 'University of Campinas (UNICAMP)',
    city: 'Campinas',
    country: 'Brazil',
    region: 'Latin America',
    specialty: 'Hematology / hemophilia',
    influenceScore: 79,
    engagementTier: 'Tier 2',
    productAlignment: ['roctavian'],
    recentInteractions: 3,
    publications: 234,
    focusAreas: ['Latin American hemophilia registries', 'Gene therapy access'],
    conferenceAppearances: 6,
    recommendedStrategy: 'Latin American access-and-registry standing is useful ex-US-credibility intelligence for informing the divestiture evaluation with real regional field data.',
  },
  {
    id: 'kol-30',
    name: 'K. John Pasi, MD, PhD',
    institution: 'Barts and The London School of Medicine, QMUL',
    city: 'London',
    country: 'UK',
    region: 'Europe',
    specialty: 'Hematology / hemophilia gene therapy',
    influenceScore: 89,
    engagementTier: 'Tier 1',
    productAlignment: ['roctavian'],
    recentInteractions: 5,
    publications: 312,
    focusAreas: ['GENEr8-1 lead UK investigator', 'Gene therapy long-term follow-up'],
    conferenceAppearances: 9,
    recommendedStrategy: 'Lead UK GENEr8-1 investigator — the strongest single ex-US scientific anchor for MO6, especially valuable given Roctavian remains available in the UK/EU post-US-withdrawal.',
  },
  {
    id: 'kol-31',
    name: 'Michael Laffan, MD',
    institution: 'Imperial College London / Imperial College Healthcare NHS Trust',
    city: 'London',
    country: 'UK',
    region: 'Europe',
    specialty: 'Hematology / hemophilia',
    influenceScore: 81,
    engagementTier: 'Tier 2',
    productAlignment: ['roctavian'],
    recentInteractions: 3,
    publications: 267,
    focusAreas: ['UK hemophilia network', 'Gene therapy safety monitoring'],
    conferenceAppearances: 7,
    recommendedStrategy: 'UK safety-monitoring standing complements Pasi for coordinated London-network MO6 field coverage under Dr. Emma Whitfield.',
  },
  {
    id: 'kol-32',
    name: 'Andrew D. Leavitt, MD',
    institution: 'University of California, San Francisco (UCSF)',
    city: 'San Francisco',
    country: 'USA',
    region: 'North America',
    specialty: 'Hematology / hemophilia gene therapy',
    influenceScore: 86,
    engagementTier: 'Tier 1',
    productAlignment: ['roctavian'],
    recentInteractions: 4,
    publications: 289,
    focusAreas: ['US gene therapy center leadership', 'Patient-selection frameworks'],
    conferenceAppearances: 8,
    recommendedStrategy: 'A key US voice for the honest, direct patient-transition conversation as US Roctavian availability ends May 2026 — priority engagement for MO6\'s domestic wind-down messaging integrity.',
  },
];
