// Predictive Signals — Command Center & NOVA. BioMarin Pharmaceutical.

export const PREDICTIVE_SIGNALS = [
  {
    id: 'ps-1',
    agent: 'NOVA',
    signal: 'SCFE-vs-achondroplasia messaging confusion (AI6) has recurred 4× — recurrence threshold exceeded',
    currentState: 'Community endocrinologists continue to ask general achondroplasia safety questions that conflate the discontinued Turner/SHOX/ACAN trials with the BioMarin-sponsored achondroplasia safety base, captured 4 separate times this cycle (Prioritised, confidence 86%). A9 (precision talking points) Accepted; A10 (safety-database one-pager) Started.',
    trajectory: 'rising',
    timeToImpact: '0–3 months',
    confidence: 'high',
    requiredAction: 'Accelerate A9 and A10 delivery to all skeletal-facing MSLs; flag as Q3 MO4 priority.',
    suggestedAction: { label: 'Review in NOVA', path: '/insights' },
  },
  {
    id: 'ps-2',
    agent: 'NOVA',
    signal: 'MO3 (MPS field excellence & Aldurazyme clarity) at Gap — internal MSL confusion confirmed',
    currentState: 'AI3 shows the Aldurazyme co-marketing confusion originates partly within BioMarin\'s own field team, not only among treating physicians — a credibility risk if left unaddressed.',
    trajectory: 'flat',
    timeToImpact: '3–6 months',
    confidence: 'medium',
    requiredAction: 'Complete A5 (internal co-marketing clarity card) and add MSL-facing training module.',
    suggestedAction: { label: 'Review in NOVA', path: '/insights' },
  },
  {
    id: 'ps-3',
    agent: 'NOVA',
    signal: 'KUVAN switching pressure (AI1) building ahead of Sephience\'s first full year on market',
    currentState: "MSL interactions show BH4-responsive PKU prescribers actively evaluating Sephience's oral, once-daily profile for stable KUVAN patients — the first real switching pressure KUVAN has faced since approval.",
    trajectory: 'rising',
    timeToImpact: '0–6 months',
    confidence: 'high',
    requiredAction: 'Complete A1 (comparison card) and A2 (BH4-responsiveness FAQ); prioritize accounts with recent Sephience inquiries.',
    suggestedAction: { label: 'Review in NOVA', path: '/insights' },
  },
  {
    id: 'ps-4',
    agent: 'LUCA',
    signal: 'Sentiment shift: Dr. Klaus Mohnike toward navepegritide ahead of EU regulatory decision',
    currentState: 'Congress debrief and MSL interaction both note unusually detailed follow-up engagement with Ascendis\'s navepegritide data — a defensible, timeline-driven attention shift ahead of the Q4 2026 EU decision, not a rupture.',
    trajectory: 'rising',
    timeToImpact: '3–6 months',
    confidence: 'medium',
    requiredAction: 'Schedule proactive BMN 333 scientific exchange (A12) before the EU decision lands.',
    suggestedAction: { label: 'Open in LUCA', path: '/kol' },
  },
  {
    id: 'ps-5',
    agent: 'ARIA',
    signal: 'WFH World Congress 2026 hallway conversation dominated by the Roctavian US-withdrawal news',
    currentState: 'Ex-US hemophilia treaters at WFH 2026 (Kuala Lumpur) directly asked whether the US withdrawal signals a broader retreat — an ex-US-credibility risk surfaced at the exact congress where BioMarin most needs to project continuity.',
    trajectory: 'rising',
    timeToImpact: '0–3 months',
    confidence: 'high',
    requiredAction: 'Accelerate A13 (ex-US credibility statement and engagement plan) across the UK/EU/international hemophilia roster.',
    suggestedAction: { label: 'Open in ARIA', path: '/congress' },
  },
  {
    id: 'ps-6',
    agent: 'NOVA',
    signal: 'US patient-transition protocol (A14) needed before May 2026 Roctavian withdrawal date',
    currentState: 'US hemophilia treatment centers report inconsistent messaging to patients mid-evaluation for Roctavian, absent a single clear field-facing transition document (AI9).',
    trajectory: 'rising',
    timeToImpact: '0–3 months',
    confidence: 'high',
    requiredAction: 'Finalize and distribute A14 to all US hemophilia-facing MSLs ahead of the withdrawal date.',
    suggestedAction: { label: 'Review in NOVA', path: '/insights' },
  },
];
